### ISSUE TITLE
I run compile.sh,got "CUDA_HOME environment variable is not set. Please set it to your CUDA install root.**"

### ISSUE THREAD

**Issue by PJSDDL** [QWTforGithub/PUDM#20]
I run compile.sh,and I got this:
**raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.**

full info as below
`Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    "/".join(__file__.split('/')[:-1] + ['chamfer3D.cu']),
  File "/home/pj/anaconda3/envs/pudm/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1047, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/pj/anaconda3/envs/pudm/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/pj/anaconda3/envs/pudm/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 2230, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
---- Chamfer3D--->Finish! ----
`

**Comment by QWTforGithub** [comment]
Hi, this may be because you did not set the CUDA_HOME environment variable, which caused the code to be unable to find nvcc to compile C++ code. 

Please try to add the following code in the ~/.bashrc:
```
vim ~/.bashrc
export CUDA_HOME=the installation path of CUDA
source ~/.bashrc
```
For example, in my environment, my installation path of CUDA is /usr/local/cuda-11.6:
`export CUDA_HOME=/usr/local/cuda-11.6`

Then, please check the current CUDA_HOME value：
`echo $CUDA_HOME`
